global:
  scrape_interval: 30s

scrape_configs:
  - job_name: booking-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - app:8080

  - job_name: insurance-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 158.180.19.25:8080

  - job_name: booking-cadvisor
    static_configs:
      - targets:
          - booking_cadvisor:8080

  - job_name: insurance-cadvisor
    static_configs:
      - targets:
          - 158.180.19.25:8082
